name: Build and push Docker image to GHCR

on:
  release:
    types: [published]
  workflow_dispatch:
env:
  CURRENT_VERSION: "25.0.3"
  BUILD_NUMBER: "0"
  IMAGE_NAME: "cruizba--ubuntu-dind"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with: 
          # bug https://github.com/docker/setup-qemu-action/issues/198
          image: tonistiigi/binfmt:qemu-v7.0.0-28

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.GITHUB_REPOSITORY_OWNER }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.REPOSITORY_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # # doesn't support dotnet in default apt repos... 
      # - name: Ubuntu 20.04 - Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     file: ubuntu-focal.Dockerfile
      #     platforms: linux/amd64,linux/arm64
      #     tags: >
      #       ghcr.io/${{ github.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:20.04,
      #       ghcr.io/${{ github.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:20.04-${{ env.CURRENT_VERSION }},
      #       ghcr.io/${{ github.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:20.04-${{ env.CURRENT_VERSION }}-r${{ env.BUILD_NUMBER }}

      - name: Ubuntu 22.04 - Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ubuntu-jammy.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: >
            ghcr.io/${{ github.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:latest,
            ghcr.io/${{ github.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:22.04,
            ghcr.io/${{ github.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:22.04-${{ env.CURRENT_VERSION }},
            ghcr.io/${{ github.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:22.04-${{ env.CURRENT_VERSION }}-r${{ env.BUILD_NUMBER }}

      - name: Ubuntu 24.04 - Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ubuntu-noble.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: >
            ghcr.io/${{ github.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:24.04,
            ghcr.io/${{ github.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:24.04-${{ env.CURRENT_VERSION }},
            ghcr.io/${{ github.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:24.04-${{ env.CURRENT_VERSION }}-r${{ env.BUILD_NUMBER }}
